import Vapor

struct AppleAuthTokenBody: Codable, Content {

    /// The identifier (App ID or Services ID) for your app. The identifier must not
    /// include your Team ID, to help mitigate the possibility of exposing sensitive
    /// data to the end user.
    let client_id: String

    /// A secret JSON Web Token, generated by the developer, that uses the Sign in
    /// with Apple private key associated with your developer account. Authorization
    /// code and refresh token validation requests require this parameter.
    let client_secret: String

    /// The authorization code received in an authorization response sent to your app.
    /// The code is single-use only and valid for five minutes. Authorization code
    /// validation requests require this parameter.
    let code: String?

    /// The grant type determines how the client app interacts with the validation
    /// server. Authorization code and refresh token validation requests require this
    /// parameter. For authorization code validation, use `authorization_code`. For
    /// refresh token validation requests, use `refresh_token`.
    let grant_type: String

    /// The refresh token received from the validation server during an authorization
    /// request. Refresh token validation requests require this parameter.
    let refresh_token: String?

    /// The destination URI provided in the authorization request when authorizing a
    /// user with your app, if applicable. The URI must use the HTTPS protocol,
    /// include a domain name, and can’t contain an IP address or localhost.
    /// Authorization code requests require this parameter.
    ///
    /// Note: When authorizing a user with your app, include the `redirect_uri` parameter
    /// only if the application provided a `redirect_uri` in the initial authorization request.
    let redirect_uri: String?

}
