apiVersion: batch/v1
kind: Job
metadata:
  name: sincereauth-release-0-2-3
  namespace: sincereauth
  labels:
    app: sincereauth-release-0-2-3
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sincereauth-release
          image: ghcr.io/fullqueuedeveloper/sincereauth-release:0.2.3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: REDIS_URL
            - name: SELF_ISSUER_ID
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: SELF_ISSUER_ID
            - name: AUTH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: AUTH_PRIVATE_KEY
            - name: APPLE_SERVICES_KEY
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: APPLE_SERVICES_KEY
            - name: APPLE_SERVICES_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: APPLE_SERVICES_KEY_ID
            - name: APPLE_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: APPLE_TEAM_ID
            - name: APPLE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: APPLE_APP_ID
            - name: DB_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: sincereauth.secrets
                  key: DB_SYMMETRIC_KEY
