apiVersion: v1
kind: Service
metadata:
  name: fqauth-service
  namespace: fqauth
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: fqauth-app
