apiVersion: v1
kind: Service
metadata:
  name: sincereauth-service
  namespace: sincereauth
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: sincereauth-app
