apiVersion: v1
kind: Service
metadata:
  name: fqauth-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: fqauth-redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: fqauth-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fqauth-redis
    spec:
      containers:
        - name: fqauth-redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - --save ""
            - --appendonly no
