name: Build
on:
  push:
    branches: "**"
    pull_request:
jobs:
  build-docker:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build .
  build-mac:
    name: Build on Mac
    runs-on: macos-11.0
    steps:
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6"
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift build -c release
