name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
#   build-docker:
#     name: Build with Docker
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - run: docker build .
#
#   build-mac:
#     name: Build on Mac
#     runs-on: macos-11.0
#     steps:
#     - uses: swift-actions/setup-swift@v1
#       with:
#         swift-version: "5.7"
#     - run: swift --version
#     - uses: actions/checkout@v2
#     - run: swift build -c release

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-11.0
        - os: ubuntu-20.04
    steps:
    - run: apt-get install -y postgres
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
    - run: initdb -U postgres -D ./postgres
    - run: pg_ctl -D ./postgres -l ./postgres.log start
    - run: psql postgresql://postgres@127.0.0.1 -c "select * from tomatoes;"
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift run FQAuthServer migrate -y --env test
    - uses: shogo82148/actions-setup-redis@v1
    - run: swift test
    env:
      DATABASE_URL: "postgresql://postgres@127.0.0.1"
      DB_SYMMETRIC_KEY: "9/Vk5Rlzctc5tyX0SCmIJaRzEg+QgwWjlTzD0LMPqNY="
      REDIS_URL: "redis://localhost"
      APPLE_SERVICES_KEY: "LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdVcmdRUUFJdz09Ci0tLS0tRU5EIEVDIFBBUkFNRVRFUlMtLS0tLQotLS0tLUJFR0lOIEVDIFBSSVZBVEUgS0VZLS0tLS0KTUlIY0FnRUJCRUlCdXRBYnNFUjY1bVFnby9iKzJYcTVsaDZQTDhuRTJSRjZ0WjFDdWNmdW5UaWtyNDFwL3JhZwpYaXd6MTJVOWxoY211Y2wrWDh5MkVacUowQ0FXS0VhTHluYWdCd1lGSzRFRUFDT2hnWWtEZ1lZQUJBQm92SWc2CkNRREdkcjMxNlR6bEJXRG56SHIvWDVoSnVzbnpSY0E2WUpUS1RVMll2bXdCaHVGUFBiNit1MUttaUdkTnQ2N1EKTU16RjMxYjY0L0gwS3prQ1BnRVZicklMVkthNDlUbTdNQU1WT3dsUUxaVHBIck8xMVk2bVd5eERydEFCSXNDTApqNnBRMFhGNlZiNWNOT3RWL1BpMC9lcTIxY3UwV3h5aDNHODY2TlQ0T1E9PQotLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tCg=="
      APPLE_SERVICES_KEY_ID: "com.fullqueuedeveloper.FQAuthServer.AppleServicesKeyID"
      APPLE_TEAM_ID: "FQDV1234"
      APPLE_APP_ID: "com.fullqueuedeveloper.FQAuth"
      AUTH_PRIVATE_KEY: "LS0tLS1CRUdJTiBFQyBQQVJBTUVURVJTLS0tLS0KQmdVcmdRUUFJdz09Ci0tLS0tRU5EIEVDIFBBUkFNRVRFUlMtLS0tLQotLS0tLUJFR0lOIEVDIFBSSVZBVEUgS0VZLS0tLS0KTUlIY0FnRUJCRUlCV1Q2RVFQZkRNelNwME1tNjFlbFRaaXljQSs5Sy9QRzN6TFFka0hsMnFlWnlCWEs4VlRrRQpTbGovemxXRkhUWG1RTTB0d3V5YnAyTEFMaHVwd2ZJR3l5eWdCd1lGSzRFRUFDT2hnWWtEZ1lZQUJBRXh5QS9wCitEM05CTmdjMm1XUjdBOVRUa0tkdWMrWVlaeFN2ZWdPMWpMeC9QbG1TUHdHcGF3c2NiYWxHYTgwbkRTNTU2SXUKR1l0S2ZnbkJGSXBFcU1FQkdBQ2MrUys2cTNBNU10emM4bHhzamRlYVlSWDdIbnJNejlVdzRROGNUUmkzUXVJNwpKdi93OEJnZFhRNnVMdGdSMTZLTzJQcVg2azRSSDdmY3BSL20vUEU1OEE9PQotLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tCg=="
