name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  test:
    name: Swift 5.6 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-11.0
        - os: ubuntu-20.04
    steps:
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6"
    - run: swift --version
    - uses: actions/checkout@v2
    - run: swift test
    - run: swift build -c release
    - run: docker build .
      if: ${{ matrix.os == 'ubuntu-20.04' }}
